-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR(30* (DAILY_FEE * (1-DISCOUNT_RATE/100))) FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY H USING (CAR_ID)
JOIN
(
SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '30일 이상'
) D USING (CAR_TYPE)
WHERE (FLOOR(30* (DAILY_FEE * (1-DISCOUNT_RATE*0.01))) BETWEEN 500000 AND 1999999)
AND C.CAR_ID NOT IN
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE NOT(END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')) AND C.CAR_TYPE IN ('세단', 'SUV')
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC