-- 코드를 입력하세요
SELECT HISTORY_ID, FLOOR(IF(DISCOUNT_RATE IS NULL, TERM * DAILY_FEE, TERM * DAILY_FEE*(100-DISCOUNT_RATE)* 0.01)) FEE
FROM
(
SELECT HISTORY_ID, CAR_ID, (TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1) AS TERM, 
       CASE WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 7 THEN '7일 이상' 
            ELSE NULL END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H
LEFT JOIN 
(SELECT DURATION_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE = '트럭') P USING(DURATION_TYPE)
JOIN CAR_RENTAL_COMPANY_CAR C USING(CAR_ID)
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC