-- 코드를 입력하세요
SELECT HOUR, MAX(COUNT)
FROM
(
(SELECT 0 HOUR, 0 COUNT) UNION
(SELECT 1, 0) UNION
(SELECT 2, 0) UNION
(SELECT 3, 0) UNION
(SELECT 4, 0) UNION
(SELECT 5, 0) UNION
(SELECT 6, 0) UNION
(SELECT 7, 0) UNION
(SELECT 8, 0) UNION
(SELECT 9, 0) UNION
(SELECT 10, 0) UNION
(SELECT 11, 0) UNION
(SELECT 12, 0) UNION
(SELECT 13, 0) UNION
(SELECT 14, 0) UNION
(SELECT 15, 0) UNION
(SELECT 16, 0) UNION
(SELECT 17, 0) UNION
(SELECT 18, 0) UNION
(SELECT 19, 0) UNION
(SELECT 20, 0) UNION
(SELECT 21, 0) UNION
(SELECT 22, 0) UNION
(SELECT 23, 0) UNION
(SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME))
) TIMETABLE
GROUP BY HOUR
ORDER BY HOUR