-- 코드를 입력하세요
SELECT concat('/home/grep/src/', F.board_id, '/',file_id, file_name, file_ext) FILE_PATH
FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE VIEWS =
(
SELECT MAX(VIEWS)
FROM USED_GOODS_BOARD
)
ORDER BY FILE_ID DESC